docs:
  - packages/react-renderer-demo/**/*

ANT:
  - packages/ant-component-mapper/**/*

common:
  - packages/common/**/*

MUI:
  - packages/mui-component-mapper/**/*

PF3:
  - packages/pf3-component-mapper/**/*

PF4:
  - packages/pf4-component-mapper/**/*

renderer:
  - packages/react-form-renderer/**/*
