language: node_js
node_js:
  - "8"

env:
  global:
    - RELEASE_DEMO=false

sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install

script: ./scripts/react-form-renderer.sh

after_success:
  - npm install -g codecov
  - npm run codecov

after_failure:
  - cat yarn-error.log

deploy:
- provider: script
  on:
    branch: master
  script: ./scripts/release.sh
  skip_cleanup: true
- provider: script
  on:
    branch: master
    script: echo env(RELEASE_DEMO)
- provider: surge
  on:
    branch: master
    condition: RELEASE_DEMO = true
  project: ./packages/react-renderer-demo/public/
  domain: data-driven-forms.surge.sh 
  skip_cleanup: true

cache:
  yarn: true
  directories:
    - ~/.npm

