language: node_js
node_js:
  - "8"

sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install

script: ./scripts/react-form-renderer.sh

after_success:
  - npm install -g codecov
  - npm install -g firebase-tools
  - npm run codecov

after_failure:
  - cat yarn-error.log

deploy:
- provider: script
  on:
    branch: master
  script: ./scripts/release.sh
  skip_cleanup: true
- provider: script
  on:
    branch: master
  script: firebase deploy --token $FIREBASE_TOKEN
  skip_cleanup: true

cache:
  yarn: true
  directories:
    - ~/.npm

