version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/react-forms
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-deps
          command: yarn
      - run:
          name: build-packages
          command: yarn build
      - run:
          name: test
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
          flags: frontend