version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/react-forms
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-deps
          command: yarn
      - run:
          name: build-packages
          command: yarn build
      - run:
          name: test
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
          flags: frontend
       - persist_to_workspace:
        root: ~/react-forms
        paths:
          - "*"
  deploy:
    working_directory: ~/react-forms
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: ~/react-forms
      - run:
          name: Authenticate with registry
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            yarn release

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
